# Generated by Django 4.1.6 on 2023-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_scrapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gifts')),
                ('link', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gift', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='GiftModel',
            new_name='GiftModelScraping',
        ),
    ]
